name: Bug Report
description: Report existing features not working properly
title: 'Bug Description'
labels: ['bug']
assignees:
  - m-scott-lassiter
body:
  - type: markdown
    attributes:
      value: |
        Thank you taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Describe what you saw
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Blender Scripting Assistant are you running?
      placeholder: ex. v1.0.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac OS
    validations:
      required: true
  - type: dropdown
    id: blender
    attributes:
      label: What version of Blender are you seeing the problem on?
      multiple: true
      options:
        - 4.1
        - 4.0
        - 3.6
        - 3.5
        - 3.4
        - 3.3
        - 3.2
        - 3.1
        - 3.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log or console output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    id: contribute
    attributes:
      label: Are you able/willing to make the change? (It's ok if you're not!)
      multiple: false
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/GraphicArtQuest/Blender-Scripting-Assistant/blob/master/CODE_OF_CONDUCT.md)
          required: true
